spring:
  application:
    name: FraudDetectionService
  redis:
    database: 0
    host: ${REDIS_HOST}
    timeout: 8000
    port: ${REDIS_PORT}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: transfer-event
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
aws:
  sqs:
    region: ${AWS_SQS_REGION}
    queueUrl: ${AWS_SQS_QUEUE_URL}
    maxNumberOfMessages: 10
    waitTimeSeconds: 2

x-rule:
  version: 0
  amountThreshold: 100000
  targetUserIds:
    - 高危用户001
  timeWindowMinutes: 5
  maxEventCount: 3
  maxConsecutiveCount: 10
  rules:
    - AMOUNT_LIMIT#1
    - BEHAVIOR_FREQUENCY#2
    - SPECIFIC_USER#2
    - CONSECUTIVE_COUNT#3