apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detect-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detect
  template:
    metadata:
      labels:
        app: fraud-detect
    spec:
      #serviceAccountName: sqs-reader-sa
      containers:
        - name: fraud-detect-app
          image: <YOUR-IMAGE-URL-IN-ECR>
          imagePullPolicy: Always
          env:
            - name: PARAMS
              value:
                --spring.kafka.bootstrap-servers=YOUR-TEST-DATA-SERVER-PRIVATE-IP:9092
                --spring.redis.host=<YOUR-TEST-DATA-SERVER-PRIVATE-IP>
                --spring.redis.port=6379
                --aws.sqs.region=<YOUR-REGION>
                --aws.sqs.queueUrl=<YOUR-SQS-URL>
                --aws.sqs.accessKey=<YOUR_AK>
                --aws.sqs.secretKey=<YOUR_SK>
          ports:
            - name: http-service
              containerPort: 8088
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http-service
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http-service
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 2

---
apiVersion: v1
kind: Service
metadata:
  name: fraud-detect-service
spec:
  ports:
    - name: http-service
      port: 8088
      targetPort: 8088
      protocol: TCP
  type: ClusterIP
  selector:
    app: fraud-detect

